services:
  tor:
    image: dperson/torproxy
    container_name: tor
    ports:
      - 8118:8118
      - 9050:9050
    restart: unless-stopped

  block-syncer:
    build: .
    container_name: block-syncer
    depends_on:
      - tor
    environment:
      - HTTP_PROXY=socks5h://tor:9050
      - HTTPS_PROXY=socks5h://tor:9050
    volumes:
      - blockdata:/app/data
      - ./logs:/app/logs      
    restart: unless-stopped

volumes:
  blockdata: